export const SET_PRICE_FOR_FIXED_MODAL = 'SET_PRICE_FOR_FIXED_MODAL';
export const SET_SEGWAY_FOR_FIXED_MODAL = 'SET_SEGWAY_FOR_FIXED_MODAL';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';

export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_TOTAL_UNIQUE_PRODUCTS = 'SET_TOTAL_UNIQUE_PRODUCTS'

export const SET_PRODUCT_MODAL = 'SET_PRODUCT_MODAL';